//! Emits idiomatic Lua against the `hl` API from a [`Config`], and re-serializes
//! a parsed [`LuaDocument`] losslessly.
//!
//! The emitted shape (confirmed against `meta/hl.meta.lua`, Hyprland 0.55.2):
//!
//! - settings via `hl.config({ ... })` (nested tables; dotted keys quoted),
//! - `hl.bind(keys, dispatcher, opts?)`, `hl.window_rule`/`hl.layer_rule`/
//!   `hl.monitor`/`hl.workspace_rule`, `hl.env`, `hl.exec_cmd`, `hl.animation`,
//!   `hl.curve`, and `$variables` as Lua `local`s.
//!
//! A few encodings are hyprconf conventions chosen for faithful round-trips
//! rather than verified API shapes — see the crate docs / CHANGELOG.

use crate::lua::document::LuaDocument;
use crate::lua::extract::escape;
use crate::model::Config;
use crate::structured::{ExecKind, Keybind};
use crate::value::Value;

/// Emits Lua from a [`Config`] (or re-prints a [`LuaDocument`] losslessly).
#[derive(Debug, Default, Clone, Copy)]
pub struct LuaSerializer;

impl LuaSerializer {
    /// Re-serialize a parsed document; byte-identical for an unedited document.
    #[must_use]
    pub fn serialize_document(document: &LuaDocument) -> String {
        document.to_text()
    }

    /// Generate fresh, idiomatic Lua from a [`Config`].
    #[must_use]
    pub fn serialize(config: &Config) -> String {
        let mut out = String::new();
        out.push_str("-- Generated by hyprconf\n\n");

        if !config.variables.is_empty() {
            for v in &config.variables {
                out.push_str(&format!(
                    "local {} = \"{}\"\n",
                    v.value.name,
                    escape(&v.value.value)
                ));
            }
            out.push('\n');
        }

        emit_config(&mut out, config);

        emit_section(&mut out, "Monitors", &config.monitors, |m| {
            let mut table = TableLit::new();
            table.str("output", &m.name);
            table.str("mode", &m.mode);
            table.str("position", &m.position);
            table.str("scale", &m.scale);
            if !m.extra.is_empty() {
                table.raw("extra", &string_array(&m.extra));
            }
            format!("hl.monitor({})", table.finish())
        });

        emit_section(&mut out, "Environment", &config.env, |e| {
            format!("hl.env(\"{}\", \"{}\")", escape(&e.name), escape(&e.value))
        });

        emit_section(&mut out, "Autostart", &config.execs, |e| {
            let cmd = format!("\"{}\"", escape(&e.command));
            match e.kind {
                ExecKind::ExecOnce => format!("hl.exec_cmd({cmd})"),
                ExecKind::Exec => format!("hl.exec_cmd({cmd}, {{ when = \"reload\" }})"),
                ExecKind::ExecShutdown => format!("hl.exec_cmd({cmd}, {{ when = \"shutdown\" }})"),
            }
        });

        emit_section(&mut out, "Keybinds", &config.keybinds, emit_bind);

        emit_section(&mut out, "Window rules", &config.window_rules, |r| {
            let mut table = TableLit::new();
            table.str("name", &r.rule);
            if !r.matchers.is_empty() {
                table.str("match", &r.matchers);
            }
            if !r.v2 {
                table.raw("v2", "false");
            }
            format!("hl.window_rule({})", table.finish())
        });

        emit_section(&mut out, "Layer rules", &config.layer_rules, |r| {
            let mut table = TableLit::new();
            table.str("name", &r.rule);
            if !r.namespace.is_empty() {
                table.str("match", &r.namespace);
            }
            format!("hl.layer_rule({})", table.finish())
        });

        emit_section(&mut out, "Workspace rules", &config.workspaces, |w| {
            let mut table = TableLit::new();
            table.str("workspace", &w.selector);
            if !w.rules.is_empty() {
                table.str("rules", &w.rules);
            }
            format!("hl.workspace_rule({})", table.finish())
        });

        emit_section(&mut out, "Bezier curves", &config.beziers, |b| {
            format!(
                "hl.curve(\"{}\", {}, {}, {}, {})",
                escape(&b.name),
                num(b.p0.x),
                num(b.p0.y),
                num(b.p1.x),
                num(b.p1.y)
            )
        });

        emit_section(&mut out, "Animations", &config.animations, |a| {
            let mut s = format!(
                "hl.animation(\"{}\", {}, {}, \"{}\"",
                escape(&a.name),
                a.enabled,
                num(a.speed),
                escape(&a.curve)
            );
            if let Some(style) = &a.style {
                s.push_str(&format!(", \"{}\"", escape(style)));
            }
            s.push(')');
            s
        });

        out
    }
}

/// Render a [`Value`] as a Lua expression.
#[must_use]
pub fn value_to_lua(value: &Value) -> String {
    match value {
        Value::Bool(b) => b.to_string(),
        Value::Int(i) => i.to_string(),
        Value::Float(x) => num(*x),
        Value::Color(c) => format!("\"{}\"", c.to_rgba_string()),
        Value::Gradient(g) => format!("\"{}\"", escape(&g.to_hyprland_string())),
        Value::String(s) => format!("\"{}\"", escape(s)),
        Value::Enum(name) => format!("\"{}\"", escape(name)),
        Value::Vec2(v) => format!("\"{}\"", v.to_hyprland_string()),
    }
}

// ---------------------------------------------------------------------------
// hl.config nested table
// ---------------------------------------------------------------------------

enum Tree {
    Leaf(Value),
    Branch(Vec<(String, Tree)>),
}

fn emit_config(out: &mut String, config: &Config) {
    let mut root: Vec<(String, Tree)> = Vec::new();
    for (path, tracked) in &config.options {
        let segs: Vec<&str> = path.split(':').collect();
        insert(&mut root, &segs, tracked.value.clone());
    }

    out.push_str("hl.config({\n");
    emit_branch(out, &root, 1);
    out.push_str("})\n");
}

fn insert(branch: &mut Vec<(String, Tree)>, segs: &[&str], value: Value) {
    let head = segs[0];
    if segs.len() == 1 {
        branch.push((head.to_string(), Tree::Leaf(value)));
        return;
    }
    let pos = branch
        .iter()
        .position(|(k, t)| k == head && matches!(t, Tree::Branch(_)));
    let idx = match pos {
        Some(i) => i,
        None => {
            branch.push((head.to_string(), Tree::Branch(Vec::new())));
            branch.len() - 1
        }
    };
    if let Tree::Branch(sub) = &mut branch[idx].1 {
        insert(sub, &segs[1..], value);
    }
}

fn emit_branch(out: &mut String, branch: &[(String, Tree)], indent: usize) {
    let pad = "    ".repeat(indent);
    for (key, node) in branch {
        let k = lua_key(key);
        match node {
            Tree::Leaf(value) => {
                out.push_str(&format!("{pad}{k} = {},\n", value_to_lua(value)));
            }
            Tree::Branch(sub) => {
                out.push_str(&format!("{pad}{k} = {{\n"));
                emit_branch(out, sub, indent + 1);
                out.push_str(&format!("{pad}}},\n"));
            }
        }
    }
}

// ---------------------------------------------------------------------------
// directive helpers
// ---------------------------------------------------------------------------

fn emit_section<T>(
    out: &mut String,
    title: &str,
    items: &[crate::model::Tracked<T>],
    render: impl Fn(&T) -> String,
) {
    if items.is_empty() {
        return;
    }
    out.push_str(&format!("\n-- {title}\n"));
    for item in items {
        out.push_str(&render(&item.value));
        out.push('\n');
    }
}

fn emit_bind(bind: &Keybind) -> String {
    let keys = if bind.mods.is_empty() {
        format!(", {}", bind.key)
    } else {
        format!("{}, {}", bind.mods, bind.key)
    };
    let dispatcher = if bind.args.is_empty() {
        bind.dispatcher.clone()
    } else {
        format!("{} {}", bind.dispatcher, bind.args)
    };

    let mut opts = TableLit::new();
    let f = &bind.flags;
    for (enabled, name) in [
        (f.locked, "locked"),
        (f.release, "release"),
        (f.repeat, "repeating"),
        (f.non_consuming, "non_consuming"),
        (f.mouse, "mouse"),
        (f.transparent, "transparent"),
        (f.ignore_mods, "ignore_mods"),
    ] {
        if enabled {
            opts.raw(name, "true");
        }
    }
    if let Some(submap) = &bind.submap {
        opts.str("submap", submap);
    }

    if opts.is_empty() {
        format!(
            "hl.bind(\"{}\", \"{}\")",
            escape(&keys),
            escape(&dispatcher)
        )
    } else {
        format!(
            "hl.bind(\"{}\", \"{}\", {})",
            escape(&keys),
            escape(&dispatcher),
            opts.finish()
        )
    }
}

fn string_array(items: &[String]) -> String {
    let inner = items
        .iter()
        .map(|s| format!("\"{}\"", escape(s)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{{ {inner} }}")
}

/// An inline `{ key = value, ... }` table literal builder.
struct TableLit {
    fields: Vec<String>,
}

impl TableLit {
    fn new() -> Self {
        Self { fields: Vec::new() }
    }

    fn str(&mut self, key: &str, value: &str) {
        self.fields.push(format!("{key} = \"{}\"", escape(value)));
    }

    fn raw(&mut self, key: &str, value: &str) {
        self.fields.push(format!("{key} = {value}"));
    }

    fn is_empty(&self) -> bool {
        self.fields.is_empty()
    }

    fn finish(self) -> String {
        format!("{{ {} }}", self.fields.join(", "))
    }
}

/// A Lua table key: bare if a valid identifier, else `["..."]`.
fn lua_key(key: &str) -> String {
    if is_lua_ident(key) {
        key.to_string()
    } else {
        format!("[\"{}\"]", escape(key))
    }
}

fn is_lua_ident(s: &str) -> bool {
    const RESERVED: &[&str] = &[
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if",
        "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
    ];
    let mut chars = s.chars();
    let first_ok = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    first_ok && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') && !RESERVED.contains(&s)
}

/// Format an `f64` without a trailing `.0` for whole numbers.
fn num(value: f64) -> String {
    if value.is_finite() && value.fract() == 0.0 && value.abs() < 1e15 {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::Color;

    #[test]
    fn value_rendering() {
        assert_eq!(value_to_lua(&Value::Bool(true)), "true");
        assert_eq!(value_to_lua(&Value::Int(10)), "10");
        assert_eq!(value_to_lua(&Value::Float(0.5)), "0.5");
        assert_eq!(value_to_lua(&Value::Float(1.0)), "1");
        assert_eq!(value_to_lua(&Value::Enum("dwindle".into())), "\"dwindle\"");
        assert_eq!(
            value_to_lua(&Value::Color(Color::rgb(255, 0, 0))),
            "\"rgba(ff0000ff)\""
        );
    }

    #[test]
    fn lua_key_quoting() {
        assert_eq!(lua_key("rounding"), "rounding");
        assert_eq!(lua_key("col.active_border"), "[\"col.active_border\"]");
        assert_eq!(lua_key("end"), "[\"end\"]");
    }
}
