// SPDX-License-Identifier: MIT OR Apache-2.0
//! Snapshot tests pinning the exact textual output of the fresh-config
//! serializers (`config_to_conf` and `LuaSerializer::serialize`). These catch
//! accidental formatting regressions that the structural round-trip tests
//! (which only assert semantic equality) would miss.

use hyprconf_core::conf::config_to_conf;
use hyprconf_core::{
    Color, Config, Exec, ExecKind, Keybind, KeybindFlags, LuaSerializer, MonitorRule, Tracked,
    Value, WindowRule,
};

/// A small but representative config: a few scalars (including a color), a
/// monitor, an autostart command, a window rule and a keybind.
fn sample_config() -> Config {
    let mut c = Config::empty();
    c.options
        .insert("decoration:rounding".into(), Tracked::new(Value::Int(8)));
    c.options
        .insert("general:gaps_in".into(), Tracked::new(Value::Int(5)));
    c.options.insert(
        "general:col.active_border".into(),
        Tracked::new(Value::Color(Color::rgba(0x33, 0xcc, 0xff, 0xee))),
    );
    c.monitors.push(Tracked::new(MonitorRule {
        name: "DP-1".into(),
        mode: "1920x1080@144".into(),
        position: "0x0".into(),
        scale: "1".into(),
        extra: Vec::new(),
    }));
    c.execs.push(Tracked::new(Exec {
        kind: ExecKind::ExecOnce,
        command: "waybar".into(),
    }));
    c.window_rules.push(Tracked::new(WindowRule {
        v2: true,
        rule: "float".into(),
        matchers: "class:^(kitty)$".into(),
    }));
    c.keybinds.push(Tracked::new(Keybind {
        flags: KeybindFlags::default(),
        mods: "SUPER".into(),
        key: "Q".into(),
        dispatcher: "killactive".into(),
        args: String::new(),
        submap: None,
    }));
    c
}

#[test]
fn conf_serializer_snapshot() {
    let expected = "\
decoration:rounding = 8
general:gaps_in = 5
general:col.active_border = rgba(33ccffee)

monitor = DP-1, 1920x1080@144, 0x0, 1
windowrulev2 = float, class:^(kitty)$
exec-once = waybar
bind = SUPER, Q, killactive
";
    assert_eq!(config_to_conf(&sample_config()), expected);
}

#[test]
fn lua_serializer_snapshot() {
    let expected = "\
-- Generated by hyprconf

hl.config({
    decoration = {
        rounding = 8,
    },
    general = {
        gaps_in = 5,
        [\"col.active_border\"] = \"rgba(33ccffee)\",
    },
})

-- Monitors
hl.monitor({ output = \"DP-1\", mode = \"1920x1080@144\", position = \"0x0\", scale = \"1\" })

-- Autostart
hl.exec_cmd(\"waybar\")

-- Keybinds
hl.bind(\"SUPER, Q\", \"killactive\")

-- Window rules
hl.window_rule({ name = \"float\", match = \"class:^(kitty)$\" })
";
    assert_eq!(LuaSerializer::serialize(&sample_config()), expected);
}
